# Generated by Django 5.0 on 2026-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
