# Generated by Django 5.0 on 2026-01-16 20:40

from django.db import migrations


def seed_permissions_and_roles(apps, schema_editor):
    """Seed initial permissions and roles."""
    PermissionModel = apps.get_model('admin_persistence', 'PermissionModel')
    RoleModel = apps.get_model('admin_persistence', 'RoleModel')
    
    # Permissions
    permissions_data = [
        {"code": "users.create", "name": "Criar Usuários", "description": "Permite criar novos usuários"},
        {"code": "users.read", "name": "Visualizar Usuários", "description": "Permite visualizar usuários"},
        {"code": "users.update", "name": "Editar Usuários", "description": "Permite editar usuários"},
        {"code": "users.delete", "name": "Deletar Usuários", "description": "Permite deletar usuários"},
        {"code": "roles.create", "name": "Criar Roles", "description": "Permite criar roles"},
        {"code": "roles.read", "name": "Visualizar Roles", "description": "Permite visualizar roles"},
        {"code": "roles.update", "name": "Editar Roles", "description": "Permite editar roles"},
        {"code": "roles.delete", "name": "Deletar Roles", "description": "Permite deletar roles"},
        {"code": "cidades.create", "name": "Criar Cidades", "description": "Permite criar cidades"},
        {"code": "cidades.read", "name": "Visualizar Cidades", "description": "Permite visualizar cidades"},
        {"code": "cidades.update", "name": "Editar Cidades", "description": "Permite editar cidades"},
        {"code": "cidades.delete", "name": "Deletar Cidades", "description": "Permite deletar cidades"},
        {"code": "cameras.create", "name": "Criar Câmeras", "description": "Permite criar câmeras"},
        {"code": "cameras.read", "name": "Visualizar Câmeras", "description": "Permite visualizar câmeras"},
        {"code": "cameras.update", "name": "Editar Câmeras", "description": "Permite editar câmeras"},
        {"code": "cameras.delete", "name": "Deletar Câmeras", "description": "Permite deletar câmeras"},
        {"code": "streaming.view", "name": "Visualizar Streaming", "description": "Permite visualizar streaming"},
        {"code": "streaming.control", "name": "Controlar Streaming", "description": "Permite controlar streaming"},
    ]
    
    permissions = {}
    for perm_data in permissions_data:
        perm, _ = PermissionModel.objects.get_or_create(
            code=perm_data["code"],
            defaults={"name": perm_data["name"], "description": perm_data["description"]}
        )
        permissions[perm_data["code"]] = perm
    
    # Roles
    admin_role, _ = RoleModel.objects.get_or_create(
        code="ADMIN",
        defaults={"name": "Administrador"}
    )
    admin_role.permissions.set(permissions.values())
    
    gestor_cidade_role, _ = RoleModel.objects.get_or_create(
        code="GESTOR_CIDADE",
        defaults={"name": "Gestor de Cidade"}
    )
    gestor_cidade_role.permissions.set([
        permissions["cidades.read"],
        permissions["cameras.create"],
        permissions["cameras.read"],
        permissions["cameras.update"],
        permissions["cameras.delete"],
        permissions["streaming.view"],
        permissions["streaming.control"],
    ])
    
    visualizador_role, _ = RoleModel.objects.get_or_create(
        code="VISUALIZADOR",
        defaults={"name": "Visualizador"}
    )
    visualizador_role.permissions.set([
        permissions["cameras.read"],
        permissions["streaming.view"],
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_persistence', '0002_usermodel_is_staff_usermodel_is_superuser'),
    ]

    operations = [
        migrations.RunPython(seed_permissions_and_roles),
    ]
