# Generated by Django 5.2.10 on 2026-01-16 14:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanoModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico - 7 dias"),
                            ("INTERMEDIARIO", "Intermediário - 15 dias"),
                            ("AVANCADO", "Avançado - 30 dias"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cidades_planos",
                "ordering": ["tipo"],
            },
        ),
        migrations.CreateModel(
            name="CidadeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                ("limite_cameras", models.IntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cidades",
                        to="cidades_persistence.planomodel",
                    ),
                ),
            ],
            options={
                "db_table": "cidades_cidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CameraModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("localizacao", models.CharField(max_length=500)),
                (
                    "url",
                    models.CharField(
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["rtsp", "rtmp"])],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVA", "Ativa"), ("INATIVA", "Inativa"), ("ERRO", "Erro")],
                        default="ATIVA",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="cidades_persistence.cidademodel",
                    ),
                ),
            ],
            options={
                "db_table": "cidades_cameras",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cidade", "status"], name="cidades_cam_cidade__d15fac_idx"
                    ),
                    models.Index(fields=["status"], name="cidades_cam_status_15aa64_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsuarioCidadeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("GESTOR", "Gestor"), ("VISUALIZADOR", "Visualizador")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="cidades_persistence.cidademodel",
                    ),
                ),
            ],
            options={
                "db_table": "cidades_usuarios_cidade",
                "ordering": ["tipo", "created_at"],
                "unique_together": {("cidade", "user_id")},
            },
        ),
    ]
